---
logstash_pipeline_config_dest_path: /etc/logstash/conf.d/logstash-5400.conf
logstash_pipeline_config_source_path: logstash-5400.conf.j2
logstash_index_pattern: elc-%{indexName}
elasticsearch_server: localhost:9200
