---
- include: java.yml
- name: add es apt-key
  apt_key:
    state: present
    url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    force_apt_get: 'yes'
    state: latest
- name: add artifacts details in sorces.list.d
  lineinfile:
    state: present
    path: '/etc/apt/sources.list.d/elastic-{{es_version}}.list'
    line: 'deb https://artifacts.elastic.co/packages/{{es_version}}/apt stable main'
    create: 'yes'